// Generated by CoffeeScript 1.10.0
(function() {
  var Watcher, request;

  Watcher = require('rss-watcher');

  request = require('request');

  exports.start = function(config) {
    var watcher;
    watcher = new Watcher(config.feed);
    watcher.set({
      feed: config.feed,
      interval: config.interval
    });
    watcher.on("new article", function(article) {
      return request.post({
        url: config.slackHook,
        body: JSON.stringify({
          "username": config.slackBotUser,
          "text": "New post: <" + article.link + "|" + article.title + ">",
          "icon_url": config.slackIcon
        }),
        headers: {
          "Content-Type": "application/json"
        }
      });
    });
    return watcher.run(function(error, articles) {
      return console.log("Started watching rss feed.");
    });
  };

}).call(this);
